version: '3'

services:
  app:
    container_name: deploy-logic_apps
    build: .
    volumes: 
      - .:/usr/src/app
    # --- uncomment below for run inactive ---
    stdin_open: true
    tty: true
    command: /bin/sh
